### ISSUE TITLE
BitTextField component cursor issue

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitframework#1642]
The cursor value must be equal to text while hovering over the input field.
Also, it must be equal to default while hovering over the text field reveal password icon.

**Comment by msynk** [comment]
it seems this issue comes from a style from the `BitDatePicker` component. since the BitDatePicker uses the BitTextField internally it kinda needed to apply such an incorrect style.
So the main issue comes from using the BitTextField in the BitDatePicker component which needs to be removed and fixed.
