### ISSUE TITLE
BitDateTimePicker Initialization

### ISSUE THREAD

**Issue by ehsangfl** [bitfoundation/bitframework#186]
Hi
System.IndexOutOfRangeException: 'No Page in PopupStack' on Initialization

This error happended when DateTimePicker.AutoClose = "True" and datetime property of ViewModel has initial value.

for example, in your sample solution, if change this line 
`<bit:BitDateTimePicker SelectedDateTime="{Binding SelectedDateTime}" Text="Please select a date!"/>`
To
`<bit:BitDateTimePicker SelectedDateTime="{Binding SelectedDateTime}" Text="Please select a date!" AutoClose="True"/>`
on BitDateTimePickerSampleView.xaml, this exception will throw on initialization of page

Bit CSharp client

BR

**Comment by ysmoradi** [comment]
We're **not** facing the same issue because there is a [workaround](https://github.com/bitfoundation/bitframework/blob/master/src/Client/Xamarin/Bit.Client.Xamarin.Prism/ViewModel/Implementations/BitPopupNavigation.cs) in Bit.Client.Xamarin.Prism
I'll move that workaround to Bit.Client.Xamarin.Controls in the upcoming release.
That exception happens in many cases, and in the end, I had to do a trick!

Note that there is a [sample](https://github.com/bitfoundation/bitframework/blob/master/Samples/CSharpClientSamples/Controls.Samples/Samples/BitDateTimePickerSampleView.xaml#L19) with AutoClose="True" in samples. I tested that and it's working fine. 

Re clone/download bitframework repo and test the latest version of sample app and let me know if you're facing that issue or not.

**Comment by ehsangfl** [comment]
this exception thrown if
1- Autoclose="True"
2-bind SelectedDate to a property ( for example property of viewmodel class )
3-Property of viewmodel must have value. not null or empty value.
Not only AutoClose="true"
I downloaded all repo after release version 5 .
if you want to see this exception, you must change this line on your sample. and then run it. dont use hotreload
Thx

**Comment by ysmoradi** [comment]
Bit 5.2 has been released. You can use that to solve your issue
